name: "Readme Tree"
description: "Automatically add the file structure tree to the corresponding position of your readme document."
author: "RavelloH"
inputs:
  showall:
    required: false
    description: "Show all files and directories(yes or no)"
    default: "no"
  showdirectoryname:
    required: false
    description: "Show directory name instead of content(yes or no)"
    default: "no"
  showchangetime:
    required: false
    description: "List the change time of the file or directory(yes or no)"
    default: "no"
  showsize:
    required: false
    description: "Lists the file or directory size(yes or no)"
    default: "no"
  showallname:
    required: false
    description: "Displays the full relative path of the file(yes or no)"
    default: "no"
  ignoregit:
    required: false
    description: "Ignore.Git folder"
    default: "yes"
runs:
  using: "composite"
  steps:
    - run: rm -rf .git/
      shell: bash
      if: ${{ inputs.ignoregit == 'yes' }}
    - run: |
        if [ ${{inputs.showall}} == 'yes' ];then showall="-a " ;else showall="" ;fi
        if [ ${{inputs.showdirectoryname}} == 'yes' ];then showdirectoryname="-d " ;else showdirectoryname="" ;fi
        if [ ${{inputs.showchangetime}} == 'yes' ];then showchangetime="-D " ;else showchangetime="" ;fi
        if [ ${{inputs.showsize}} == 'yes' ];then showsize="-s " ;else showsize="" ;fi
        if [ ${{inputs.showallname}} == 'yes' ];then showallname="-f " ;else showallname="" ;fi
        tree ${showall}${showdirectoryname}${showchangetime}${showsize}${showallname}
  
      shell: bash
    - run: ${{ github.action_path }}/tree.sh
      shell: bash
